CREATE DATABASE BD_PRUEBA_UPC_CARLOS_RAMOS
GO

USE BD_PRUEBA_UPC_CARLOS_RAMOS
GO

CREATE TABLE TB_ALUMNO (
    IdAlumno INT IDENTITY NOT NULL,
	Nombres NVARCHAR(50) NOT NULL,
	Apellidos NVARCHAR(50) NOT NULL,	     
    CONSTRAINT PK_TB_ALUMNO PRIMARY KEY (IdAlumno)    
)
GO

CREATE TABLE TB_CURSO (
    IdCurso INT IDENTITY NOT NULL,
	Nombre NVARCHAR(100) NOT NULL,
	Descripcion NVARCHAR(500) NOT NULL,
	NroCreditos INT NOT NULL,
	Activo BIT  NOT NULL,
    CONSTRAINT PK_TB_CURSO PRIMARY KEY (IdCurso)    
)
GO

CREATE TABLE TB_SOLICITUD (
	IdSolicitud INT IDENTITY NOT NULL,
    IdAlumno INT NOT NULL,
    FechaSolicitud DATETIME NOT NULL,
	CodRegistrante NVARCHAR(8) NOT NULL,
	Carrera NVARCHAR(200) NOT NULL,
	Periodo NVARCHAR(15) NOT NULL,

    CONSTRAINT PK_TB_SOLICITUD PRIMARY KEY (IdSolicitud),
    CONSTRAINT FK_TB_SOLICITUD_TB_ALUMNO FOREIGN KEY (IdAlumno) REFERENCES TB_ALUMNO(IdAlumno)
)
GO

CREATE TABLE TB_DETALLE_SOLICITUD (

	IdDetalleSol INT IDENTITY NOT NULL,
	IdSolicitud INT NOT NULL,
    IdCurso INT NOT NULL,
	Profesor NVARCHAR(200) NOT NULL,
	Aula NVARCHAR(100) NOT NULL,
	Sede NVARCHAR(200) NOT NULL,
	Observacion NVARCHAR(500) NOT NULL,

    CONSTRAINT PK_TB_DETALLE_SOLICITUD PRIMARY KEY (IdDetalleSol),
    CONSTRAINT FK_TB_DETALLE_SOLICITUD_TB_SOLICITUD FOREIGN KEY (IdSolicitud) REFERENCES TB_SOLICITUD(IdSolicitud),
    CONSTRAINT FK_TB_DETALLE_SOLICITUD_TB_CURSO FOREIGN KEY (IdCurso) REFERENCES TB_CURSO(IdCurso)
)
GO